name: Test Github Actions
on:
  push:
    branches:
      - master
jobs:
  hello_actions:
    name: Hello Actions
    id: hello_actions
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo "Hello world"
          npm install
          npm test
      - name: Second test after test
  second_step:
    name: My second step
    runs-on: ubuntu-latest
    needs: [hello_actions]
    steps:
      - name: First steo second job
