name: Test Github Actions
on:
  push:
    branches:
      - master
jobs:
  hello_actions:
    name: Hello Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: First step
        run: |
          echo "Hello world"
          npm install
          npm test
      - name: Second test after test
        run: echo "Se me ha olvidado..."
  second_step:
    name: My second step
    runs-on: ubuntu-latest
    needs: [hello_actions]
    steps:
      - name: First steo second job
        run: echo "Finalizado todo"
