name: Hello Github Workflow
on:
  push:
    branches:
      - master
jobs:
  run_tests:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependecy
        run: npm install
      - name: Run test
        run: npm test
  second_step:
    name: My second step
    runs-on: ubuntu-latest
    needs: [run_tests]
    steps:
      - name: Login Heroku
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a test-github-action web 
        